print(100>80)
print(155<17)
print(25==10)
print(255!=111)
print(10>=12)
print(10<=11)
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(bool(0))
print(bool(3))
